### ISSUE TITLE
score identifier

### ISSUE THREAD

**Issue by saubin78** [agroportal/fairness#23]
O'FAIR ne semble pas reconnaitre un DOI  sous la forme http://doi.org/10.15454/1.5077147058936785E12 
http://agroportal.lirmm.fr/ontologies/ASCOPAIN-T n'a que 6 points et pourtant un DOI valide

Super les explications du calcul ! on a tout de suite envie d'améliorer ses métadonnées :-)

**Comment by jonquet** [comment]
Reproduced as in the image

![image](https://user-images.githubusercontent.com/7379183/153376848-851815dd-7932-4804-99b0-46529ad582c5.png)

@syphax-bouazzouni Can you point to the the test in the code so that we double check?

**Comment by syphax-bouazzouni** [comment]
Fixed (see screen below)
<img width="836" alt="image" src="https://user-images.githubusercontent.com/29259906/153388344-9c96d55f-0314-4880-be05-c9af81fa4580.png">

Merci @saubin78  pour votre retour.
