### ISSUE TITLE
scpre A1Q1 : Does the ontology URI and other identifiers, if exist, resolve to the ontology?

### ISSUE THREAD

**Issue by saubin78** [agroportal/fairness#24]
6 points for this question, isn't too low?

**Comment by jonquet** [comment]
Hi @saubin78 
I understand you think it's not enough point (6/478) for the aspect related to the identifier. In fact this question (A1Q1) only checks the fact that the identifier explicitly resolve to the ontology. 

Related to identifiers we also have F1Q1 (9 pts), F1Q2 (11 pts), F1Q3 (12 pts), F1Q4 (9 pts) whcih means that overall identifiers well managed  for an ontology will give 47/478 which is arround 10% ! 

The number of credits available for F1 was determined as explained in https://hal.archives-ouvertes.fr/lirmm-03208544/

![image](https://user-images.githubusercontent.com/7379183/153375668-aafcdf1f-e5c7-4ec3-8391-ad71bab6e741.png)

**Comment by saubin78** [comment]
Thanks for the explanation. You are right
