### ISSUE TITLE
Visualisation O’FAIRe dans le SIFR BioPortal cassée 

### ISSUE THREAD

**Issue by jonquet** [agroportal/fairness#25]
La page d’accueil n’affiche plus le composant.

**Comment by jonquet** [comment]
Il est possible que cela entraîne le non affichage de la page Browse et des pages Summary aussi. Ouch !

**Comment by syphax-bouazzouni** [comment]
Seems to be fixed 

![Image](https://user-images.githubusercontent.com/29259906/183725222-a7acaf6d-af7d-45d3-b197-e0e153ce3fb2.png)

I will close this issue like there are yet other issues to track O'FAIRE issues
