### ISSUE TITLE
Question about O'FAIRe for TAXREF-LD

### ISSUE THREAD

**Issue by jonquet** [agroportal/fairness#28]
### De @frmichel abou TAXREF-LD in AgroPortal

Concernant la note de FAIRness, évidemment j'ai pleins de questions pour améliorer notre score ! ;)
Il va falloir regarder dans le détail, mais voici rapidement quelques points que j'ai remarqués :

"Metadata vocabulary used local:local" : d'où vient ce local:local ?

> F3Q1 : Are the ontology metadata included and maintained in the ontology file?

Les métadata font en effet partie de la distribution, comme un [fichier séparé](https://github.com/frmichel/taxref-ld/blob/master/dataset/Taxrefld_static_dataset_description.ttl) qui devrait être dans le single file que je t'ai fourni. Non ?

> A1Q1 : Does the ontology URI and other identifiers, if exist, resolve to the ontology?

http://taxref.mnhn.fr/lod/taxref-ld est bien déréférencé vers l'ongologie. Quel est le pb ?

> I1Q5 : Is the availability of other syntaxes/formats informed? 

Quelles sont les valeurs attendues pour dct:hasFormat ?

> I2Q2 : Does the ontology reuse terms from other FAIR vocabularies (URIs)? 

Je déclare ça, est-ce ça ne suffit pas ? Comment savoir s'ils sont FAIR eux-mêmes ?
void:vocabulary
        skos:, skosxl:, dct:, foaf:, schema:, bibo:, <http://www.wikidata.org/>, <http://sws.geonames.org/>,
        ro:, dwc:, dwciri:,
        <http://aims.fao.org/aos/agrovoc/>, <http://lod.taxonconcept.org/ontology/txn.owl>, <http://purl.obolibrary.org/obo/ncbitaxon.owl>, <http://purl.obolibrary.org/obo/envo.owl>, <http://rdf.geospecies.org/ont/geospecies.owl>, <http://rs.tdwg.org/ontology/voc/TaxonRank>, <http://rs.tdwg.org/ontology/voc/TaxonName>, <http://rs.tdwg.org/dwc/terms/>;

> I2Q4 : Is the ontology aligned to other FAIR vocabularies? + I2Q5 + I2Q6

Même remarque, j'ai des alignements avec pas mal de vocabulaires genre ENVO, UBERON, Wikidata etc. Ils sont explicités ([exemple](https://github.com/frmichel/taxref-ld/blob/master/dataset/Taxrefld_static_defs_habitats.ttl)), ça ne suffit pas ? Ce n'est pas pris en compte ?

I3Q1, I3Q2, et R1Q3 à R1Q6  ne peuvent pas être évaluées : pourquoi ?

**Comment by jonquet** [comment]
> "Metadata vocabulary used local:local" : d'où vient ce local:local ?
Ce champ est une erreur introduite par notre interface graphique. Il faut explicitement l'enlever. 
Ce problème doit etre fixé bientôt. 

> F3Q1
Alors dans l'implementation d'AgroPortal de la methodology O'FAIRe nous ne donnons aucun point a F3Q1 que nous ne pouvons pas facilement verifier de manière générale mais donnons tous les points a F3Q2 et F3Q3 pour etre equivalent. En gros, nous nous reposons sur le fait que AgroPortal établit explicitement le lien entre le fichier de metadonnées (celui d'AgroPortal) et l'ontologie. 

>A1Q1 
Bon point cela semble être un bug chez nous =>

**Comment by jonquet** [comment]
@fmichel : la suite pendant l'AgroHackathon 2022 à Montpellier !

**Comment by frmichel** [comment]
@jonquet @syphax-bouazzouni: A propos de I1Q5 dct:hasFormat et dct:isFormatOf, est-ce que `dcat:distribution [ dcat:mediaType      <http://www.iana.org/assignments/media-types/text/turtle>; ]` peut suffire ou faut-il impérativement utiliser les dct:* ?

**Comment by jonquet** [comment]
>A propos de I1Q5 dct:hasFormat et dct:isFormatOf, est-ce que dcat:distribution [ dcat:mediaType <http://www.iana.org/assignments/media-types/text/turtle>; ] peut suffire ou faut-il impérativement utiliser les dct:* ?

Alors bonne question. Pour extraire automatiquement le champ dans AgroPortal, il nous faut dct:hasFormat et dct:isFormatOf car nous n'avons pas troyvé de "mappigns" pour ces propriétés dans [MOD1.4](https://github.com/sifrproject/MOD-Ontology/blob/master/versions/mod-v1.4_profile.rdfs). Cependant, tu peux le representer dans ta métadonnées comme tu le proposes, et juste saisir dans AgroPortal les métadonnées manuellement; ce qui est édité est la "copie" du record dans AgroPortal, pas le record lui meme.

La raison pour laquelle la propriété dcat:distribution n'est pas incluse est parce que lorsque nous avons fait MOD et sélectionné les propriétés des vocabulaires de métadonnées, nous avons prise, dans le cas de DCAT v2, celles de l'objet dcat:Distribution qui n'a pas la propriété dcat:distribution => c'est une des limites de MOD1.4 vis a vis de DCAT et c'est aussi pourquoi MOD2 est désignée pour etre un "profil de DCAT" et intégré cette vision Dataset/Distribution plus nativement.

**Comment by jonquet** [comment]
>I2Q2 : dct:relation doit donc donner non pas des vocabulaires mais les termes réutilisés dans chaque vocabulaire, c'est bien ça ? Chacun de ces vocabulaires pouvant par ailleurs être donné par void:vocabulary.

Non. Les cibles sont bien des vocabulaires/ontologies "réutilisés" ...si c'était les termes ce ne serait pas une métadonnée, mais bien une donnée. Donc on fait confiance a l'utilisateur qui dit "ONTO1 dct:relation ONTO2" sur le fait que l'ontologie ONTO1 "réutilise" bien des termes de ONTO2. Je mets "reutilise" entre guillemet et nous avons volontairement choisi dct:relation considérant l'ambiguïté de ce mot... la réutilisation d'une ontologie étant prenant des formes très variées. 

Nous affichons dct:relation dans l'UI (qui est celle recommandée par MOD) mais dans le backend nosu pouvons reconnaitre les 4 propriétés ci dessous : 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/7379183/183460844-715eadd0-07a5-4d83-be5a-01d955f69754.png">

Attention, I2Q2 évalue que la réutilisation d'ontologies (en gros pour compléter le contenu de la l'ontologie qui réutilise).
La réutilisation de vocabulaires de métadonnées pour décrire ce contenu (e.g., le fait qu'une ontologie se repose sur DC ou SKOS ou VOAF) est évaluée par I2Q7. 
Similairement, l'alignement (qui est un cas special et précis de "réutilisation") est évalué par I2Q4

**Comment by jonquet** [comment]
> I2Q4: dans ton snapshot la note des de 5/5 mais sur http://stageportal.lirmm.fr/ontologies/TAXREF-LD/?p=summary#I2Q4 je vois 0/5. Tu as regardé ça où ?

J'ai prise cela sur la version en production sur AgroPortal dans laquelle tu avais du éditer qq champs de métadonnées dont celui sur les alignements. La encore, on fait confiance a l'utilisateur qui remplie ce champs, on ne vérifie pas en regardant si le contenu de l'ontologie est bien alignée a une autre ontologie.
