### ISSUE TITLE
Bug with A1Q1 on TAXREF-LD

### ISSUE THREAD

**Issue by jonquet** [agroportal/fairness#29]
On TAXREF-LD, OFAIRe in AgroPortal does not assing point to A1Q1 : 

<img width="696" alt="image" src="https://user-images.githubusercontent.com/7379183/179693113-883bd35f-3e8f-4137-b85c-1f584e2106cc.png">

Where as http://taxref.mnhn.fr/lod/taxref-ld seems resolvable.

**Comment by syphax-bouazzouni** [comment]
It seems that it got resolved by itself.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/29259906/186902342-16ea890f-9e3c-430c-b424-fe9ec71ca980.png">

I think that is just that the change was made in Agroportal but we had to wait for the night cache refresh to see the updated scores.
