### ISSUE TITLE
Enable O'FAIRe on MatPortal 

### ISSUE THREAD

**Issue by huanyu-li** [agroportal/fairness#30]
Hi,

My ontology is hosted at github and is available at matportal (does not support fairness yet I think). May I ask how should I use the tool? For instance, can I do sth like (http://services.agroportal.lirmm.fr/ofaire?url=http://w3id.org/mdo/structure/1.1/)? 

Best,
Huanyu

**Comment by syphax-bouazzouni** [comment]
HI @huanyu-li,

no it is not possible to do `http://services.agroportal.lirmm.fr/ofaire?url=http://w3id.org/mdo/structure/1.1/`, the ofaire service works only if its hosted on [Agroportal](http://agroportal.lirmm.fr/), [SIFR Bioporta](http://bioportal.lirmm.fr/)l or [Industryportal ](http://industryportal.enit.fr/)

**Comment by jonquet** [comment]
Hi @huanyu-li
You should transfer your requirement to Alexandru-Aurelain Todor who is maintaining MatPortal. 
He could reach out to us to "install" O'FAIRe in MatPortal.  
We are all connected in the OntoPortal Alliance, but I suspects that the requirements need to go to Alexandru-Aurelain  first.

**Comment by syphax-bouazzouni** [comment]
No news on that @alexandrutodor ?
