### ISSUE TITLE
How to add the O’FAIRe UI to an OntoPortal instance ?

### ISSUE THREAD

**Issue by chris-day** [agroportal/fairness#32]
Hi - I would like to add the O’FAIRe UI interface to my local OntoPortal instance. Is this possible?

**Comment by syphax-bouazzouni** [comment]
Hi @chris-day; 

O'FIARE is deeply related to the Agroportal version of code. So it is slightly complex to have it without updating your code to ours.

And to do that here are the steps:

A - Connecting to Ontoportal LIRMM branch( Agroportal branch):

In the ontoportal project (https://github.com/ontoportal)

Fork the "ontoportal_web_ui", "ontologies_api" and "ncbo-cron" repositories.

Merge the "ontoportal-lirrm" branch into the master of all your repositories

Deploy the code in your appliance/server.


B - Deploy the O'FAIRE service on your servers/appliance:

Refer to https://github.com/agroportal/fairness for instructions.

**Comment by chris-day** [comment]
Hi @syphax-bouazzouni -

Many thanks for your expertise, as usual. I'm a few steps behind, using the wrapped BioPortal VM rather than building from OntoPortal source. I'll raise an issue on OntoPortal for building from scratch, then try the O'FAIRE steps out.
